[tools]
node = "24.11.0"
go = "1.25.1"
ruby = "3.4.3"
python = "3.14.0"
uv = "0.8.6"
rust = { version = "stable", profile = "default", components = "rust-analyzer" }

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
python.uv_venv_auto = true
